"""
fewshot_retrievers.py
=====================
Sparse, dense, and hybrid retrieval over the few-shot example store.

The store is generated by `experiments/rebuild_all_artifacts.py` and consists of:
- JSON example exports for BM25 / hybrid lexical retrieval
- Chroma collections for dense retrieval

This module only implements retrieval. Prompt assembly policy remains separate.
"""

from __future__ import annotations

import numpy as np
from rank_bm25 import BM25Okapi

from components.config import (
    EMBEDDING_MODEL,
    FEWSHOT_CHROMA_PATH,
    FEWSHOT_COLLECTION_BINARY,
    FEWSHOT_COLLECTION_MULTICLASS,
)
try:
    from utils import load_fewshot_examples, tokenize
except ModuleNotFoundError:
    from retriever.utils import load_fewshot_examples, tokenize

RRF_K = 60

_fewshot_embedding_model = None
_fewshot_collections: dict[str, object] = {}


def initialise_fewshot_dense_retrieval(
    *,
    chroma_path: str = str(FEWSHOT_CHROMA_PATH),
    embedding_model_name: str = EMBEDDING_MODEL,
) -> None:
    import chromadb
    import torch
    from sentence_transformers import SentenceTransformer

    global _fewshot_embedding_model, _fewshot_collections

    device = "cuda" if torch.cuda.is_available() else "cpu"
    print(f"Loading few-shot embedding model on {device} ...")
    _fewshot_embedding_model = SentenceTransformer(embedding_model_name, device=device)

    client = chromadb.PersistentClient(path=str(chroma_path))
    _fewshot_collections = {
        "multiclass": client.get_collection(FEWSHOT_COLLECTION_MULTICLASS),
        "binary": client.get_collection(FEWSHOT_COLLECTION_BINARY),
    }
    print(
        "Few-shot collections ready:",
        {
            head: collection.count()
            for head, collection in _fewshot_collections.items()
        },
    )


def _require_dense(head: str) -> object:
    if _fewshot_embedding_model is None or head not in _fewshot_collections:
        raise RuntimeError(
            "Few-shot dense retrieval not initialised. "
            "Call initialise_fewshot_dense_retrieval() first."
        )
    return _fewshot_collections[head]


class FewShotBM25Retriever:
    def __init__(self, *, head: str, examples: list[dict] | None = None, json_path: str | None = None):
        self.head = head
        self.examples = examples if examples is not None else load_fewshot_examples(json_path, head=head)
        self.tokenized_examples = [tokenize(example.get("post", example.get("text", ""))) for example in self.examples]
        self.bm25 = BM25Okapi(self.tokenized_examples)
        print(f"Few-shot BM25 retriever ready: {head} ({len(self.examples)} examples)")

    def search(self, query: str, k: int = 5) -> list[dict]:
        if not query or not query.strip():
            return []

        tokenized_query = tokenize(query)
        if not tokenized_query:
            return []

        scores = self.bm25.get_scores(tokenized_query)
        ranked_indices = np.argsort(scores)[::-1]

        rows: list[dict] = []
        for idx in ranked_indices:
            if scores[idx] <= 0:
                continue
            row = self.examples[idx].copy()
            row["bm25_score"] = float(scores[idx])
            rows.append(row)
            if len(rows) >= k:
                break
        return rows


class FewShotDenseRetriever:
    def __init__(self, *, head: str):
        if head not in {"multiclass", "binary"}:
            raise ValueError(f"Unsupported head: {head}")
        self.head = head

    def search(self, query: str, k: int = 5) -> list[dict]:
        if not query or not query.strip():
            return []

        collection = _require_dense(self.head)
        query_embedding = _fewshot_embedding_model.encode(
            [query],
            normalize_embeddings=True,
        ).tolist()

        results = collection.query(
            query_embeddings=query_embedding,
            n_results=k,
            include=["documents", "metadatas", "distances"],
        )

        rows: list[dict] = []
        ids = results.get("ids", [[]])[0]
        for i in range(len(results["documents"][0])):
            meta = results["metadatas"][0][i]
            doc = results["documents"][0][i]
            dist = results["distances"][0][i]
            rows.append(
                {
                    "id": ids[i] if i < len(ids) else f"{self.head}_{i}",
                    "head": meta.get("head", self.head),
                    "label": meta["label"],
                    "post": doc,
                    "text": doc,
                    "source_split": meta.get("source_split", "source"),
                    "dense_score": 1 - dist,
                }
            )
        return rows


class FewShotHybridRetriever:
    def __init__(
        self,
        *,
        head: str,
        examples: list[dict] | None = None,
        json_path: str | None = None,
        alpha: float = 0.3,
        rrf_k: int = RRF_K,
    ):
        self.head = head
        self.alpha = alpha
        self.rrf_k = rrf_k
        self.bm25 = FewShotBM25Retriever(head=head, examples=examples, json_path=json_path)
        self.dense = FewShotDenseRetriever(head=head)

    def _fuse(self, bm25_results: list[dict], dense_results: list[dict]) -> list[dict]:
        bm25_ranks = {r["id"]: i + 1 for i, r in enumerate(bm25_results)}
        dense_ranks = {r["id"]: i + 1 for i, r in enumerate(dense_results)}

        row_by_id = {r["id"]: r for r in bm25_results}
        row_by_id.update({r["id"]: r for r in dense_results})

        fused: list[dict] = []
        for row_id, row_src in row_by_id.items():
            bm25_rank = bm25_ranks.get(row_id)
            dense_rank = dense_ranks.get(row_id)

            score = 0.0
            if bm25_rank is not None:
                score += self.alpha / (self.rrf_k + bm25_rank)
            if dense_rank is not None:
                score += (1 - self.alpha) / (self.rrf_k + dense_rank)

            row = row_src.copy()
            row["hybrid_score"] = score
            row["score"] = score
            row["bm25_rank"] = bm25_rank
            row["dense_rank"] = dense_rank
            fused.append(row)

        fused.sort(key=lambda x: x["hybrid_score"], reverse=True)
        return fused

    def search(self, query: str, k: int = 5) -> list[dict]:
        if not query or not query.strip():
            return []

        bm25_results = self.bm25.search(query, k=k)
        dense_results = self.dense.search(query, k=k)
        return self._fuse(bm25_results, dense_results)[:k]


def build_fewshot_retrievers(*, head: str, alpha: float = 0.3) -> dict[str, object]:
    examples = load_fewshot_examples(head=head)
    return {
        "bm25": FewShotBM25Retriever(head=head, examples=examples),
        "dense": FewShotDenseRetriever(head=head),
        "hybrid": FewShotHybridRetriever(head=head, examples=examples, alpha=alpha),
    }

